### ISSUE TITLE
Infomation of CPU, Disk, Ram not loading

### ISSUE THREAD

**Issue by daicadung** [jbelien/OVH-Monitoring#8]
Dear, I have problem.
My account have 3x vps.
I installed your code, but infomation still loading.
Demo: http://dungx.net/ovh/public/vps.php
You can check ?

**Comment by jbelien** [comment]
Hi @daicadung ,

It seems that the whole page is not loaded !
If you check at the source code of the page, you'll see that it ends by
```
<td colspan="18" class="text-right small text-muted">
```

I guess there is an error in the page !
Can you enable the error display or paste here the error from the error log ?

**Comment by daicadung** [comment]
Call to undefined function _() in /home/istneduv/public_html/ovh/public/vps.php on line 140.

**Comment by jbelien** [comment]
You need to install and enable PHP `gettext` extension.

**Comment by jbelien** [comment]
@daicadung I see now that the page is loaded correctly but it seems to ba an error while querying the API.

Could you send me the error log again ? :)
Thanks !

**Comment by daicadung** [comment]
@jbelien Dear
New error: https://pastebin.com/EXiq6k2q
Pls check help me.

**Comment by jbelien** [comment]
Apparently, the app does not find `monitoring.ini` file.

Did you create `monitoring.ini` file next to `public` directory with those parameters ?

```
application_key    = your_application_key
application_secret = your_application_secret
endpoint           = ovh-eu
consumer_key       = your_consumer_key
```

**Comment by daicadung** [comment]
Yes.
I have create monitoring file in public folder.
display_errors enabled
